* 2016/07/21 16:21:41 - fundamentals.logs - ERROR (/usr/local/lib/python2.7/site-packages/sloancone-0.3.2-py2.7.egg/sloancone/check_coverage.py > _query_sdss > 138) - could not determine whether object is in SDSS DR12 footprint - failed with this error local variable 'response' referenced before assignment:   
